name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BASE_PATH: '/kusogaki-web'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run lints
        run: yarn lint

      - name: Build site
        run: yarn build

      - name: Upload build and .svelte-kit folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build

  deploy:
    # Only run if merged to main.
    if: github.ref == 'refs/heads/main'
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
